### ISSUE TITLE
Deliver websocket-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/websocket-api#322]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
https://projects.eclipse.org/projects/ee4j.websocket/releases/2.0
- [x] **~~Initiate a ballot for your Jakarta Release Record/Plan.~~** - n/a
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by joakime** [comment]
# Completed

* **Jakarta-ize your Specification document** - done in PR #315 
* **javax -> jakarta API updates** - done in PR #312 
* **javax -> jakarta Spec updates** - done in PR #312

# Not Applicable

*  **javax -> jakarta Compatible Implementation updates** - this belongs to the https://github.com/eclipse-ee4j/tyrus project

**Comment by joakime** [comment]
The jakarta websocket API 2.0.0-M1 is now present on maven central.

Does that satisfy the **Release Candidate (RC) of Jakarta API in Maven Central** todo?

**Comment by kwsutter** [comment]
Thanks, @joakime!  Although the CI updates do belong to the Tyrus project, this Specification Project still has to monitor that progress.  When the final PRs are delivered for the Spec and Apiddoc updates, one of the requirements for a new Specification Version is to reference a working CI that supports the updates.  So, eventually, it will come into play...

I equate Milestone drivers with RC drivers, so yes that would suffice.  Do you have the Maven coordinates available?

**Comment by joakime** [comment]
> I equate Milestone drivers with RC drivers, so yes that would suffice. Do you have the Maven coordinates available?

Here you go.

``` xml
<!-- for Server -->
<dependency>
  <groupId>jakarta.websocket</groupId>
  <artifactId>jakarta.websocket-api</artifactId>
  <version>2.0.0-M1</version>
</dependency>

<!-- for Client -->
<dependency>
  <groupId>jakarta.websocket</groupId>
  <artifactId>jakarta.websocket-client-api</artifactId>
  <version>2.0.0-M1</version>
</dependency>

```

**Comment by kwsutter** [comment]
Hi, I see websocket-all 2.0.0-M1 in Maven Central, but not the individual Server and Client APIs:
https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-all/2.0.0-M1 
https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-api 
https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-client-api 

Did these get published or are they still in a staging repo?

**Comment by markt-asf** [comment]
Let me check the CI build. Note M1 is definitely a Milestone, not an RC. I was only looking to get a version out using the jakarta package for other projects that needed the dependency. I didn't check any other stuff at all. There could be all sorts wrong with it.

**Comment by joakime** [comment]
> Hi, I see websocket-all 2.0.0-M1 in Maven Central, but not the individual Server and Client APIs:
> https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-all/2.0.0-M1
> https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-api
> https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-client-api
> 
> Did these get published or are they still in a staging repo?

Don't use _mvnrepository.com_ it's not reliable, out of date, and often gives you false information.

https://search.maven.org/ is the official search website.

Example: https://search.maven.org/search?q=g:jakarta.websocket%20AND%20v:2.0.0-M1

The official jars for 2.0.0-M1 are ...

* https://search.maven.org/artifact/jakarta.websocket/jakarta.websocket-all/2.0.0-M1/pom - this is a pom, it's has no jar release
* https://search.maven.org/artifact/jakarta.websocket/jakarta.websocket-api/2.0.0-M1/bundle - this is the server jar (it's declared as a `bundle` per the glassfish requirements, but it's actually the main server jar)
* https://search.maven.org/artifact/jakarta.websocket/jakarta.websocket-client-api/2.0.0-M1/bundle - this is the client jar

Seen as direct jar downloads ...

* https://repo1.maven.org/maven2/jakarta/websocket/jakarta.websocket-api/2.0.0-M1/jakarta.websocket-api-2.0.0-M1.jar
* https://repo1.maven.org/maven2/jakarta/websocket/jakarta.websocket-client-api/2.0.0-M1/jakarta.websocket-client-api-2.0.0-M1.jar

**Comment by joakime** [comment]
> Note Tomcat already has a working implementation of the new API so we don't necessarily have to wait on Tyrus. What we do need is the updated TCK.

Per the TODO list it seems that we are on the hook for updating the TCK.
That's easily the most time consuming task on the TODO list.

_Opinion:_ It would be easier (and faster) to develop a standalone TCK from scratch (like CDI / weld did) then updating the existing giant ball of spaghetti that is the official TCK. (Plus we can actually get proper coverage for the Client portions which the official TCK seems to have not done)

**Comment by markt-asf** [comment]
The TCK project recently posted instructions for building and running the stand-alone TCKs. My plan was to build and run the WebSocket TCK and then see what needed to be changed for 2.0 (actually was going to start with EL as it is quicker to run but the same idea applies). I'd like to get a sense of how much work that is before contemplating a complete replacement of the TCK. My sense is that a complete replacement is far more work.

**Comment by kwsutter** [comment]
Thanks for the information on mvnrepository, @joakime.  Point well taken.

FYI, some TCKs are standalone, others are part of the platform TCK.  The idea of the checklist item is to track that the TCK needs to be updated accordingly.  It may be members of the Spec project, it may be someone else.

I thought the Web Socket TCK was already standalone, but maybe I'm mistaken.

**Comment by kwsutter** [comment]
Also, on the Platform Call this morning, the difference between Milestone and RC drivers was explained.  A Milestone driver is just one step towards a Release.  It's very preliminary and considered not functionally complete.  Release Candidates are used to show progress towards a final Release.  To that end, we are interested in a Release Candidate URL for the APIs, not Milestone drivers.  I'll clarify in my next note the wider team as well.

**Comment by markt-asf** [comment]
The M1 release from WebSocket (and EL, Servlet and JSP when the PR is approved) are feature complete from a code perspective but I don't consider them good enough for an RC because I know I haven't checked anything else (e.g. version details in Manifest, copyright headers, changelogs, etc.). We should be able to do that fairly quickly but the intention, for those projects at least, was that the M1 would be 'good enough' for dependent projects to work with. The Servlet M1 and El M1 are good enough, for example, to enable JSP to progress.

**Comment by kwsutter** [comment]
@markt-asf This sounds like great progress!  I would suggest just creating RC releases for the APIs that you are referencing.  That way everyone knows that the API is usable for testing.  Milestone drivers have a different definition and, thus, users wouldn't know whether they should be used or not.  Thanks!

**Comment by kwsutter** [comment]
Can I ask this team to please create and assign the following labels to this Issue? Thank you!
[wave:1]

**Comment by kwsutter** [comment]
Now that we have come to the conclusion that Milestone APIs are sufficient for the respective column in our Project Plan, can I ask that we create a [Notecard in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-7346435) for your M1 jar files?  Thank you!

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by markt-asf** [comment]
https://github.com/jakartaee/specifications/pull/199
https://github.com/jakartaee/specifications/pull/200

**Comment by kwsutter** [comment]
Looking for an update on the status of the Web Socket Final Specification PR.  If we're going to make the [Sept deliverable goal](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9#jakarta-ee-9-schedule), then this Wave 1 Specification needs to be ready for final ballot by Monday, July 19.  Which means that the Specification PRs should already be created and under a "mentorship" review.  Can I ask what the plans are for this Specification?  Thanks!

**Comment by joakime** [comment]
Looks like the 2 specification PRs mentioned by @markt-asf were merged.

**Comment by markt-asf** [comment]
WebSocket should be ready to go for the final release. I don't see any outstanding issues. I'll give it 24 hours or so and if no objects start the release process for 2.0.0.

**Comment by joakime** [comment]
Had a look around at the open/closed issues, i'm good with the release of 2.0.0 as it stands right now.

**Comment by kwsutter** [comment]
Excellent!  Please create your draft Specification PR(s) at your earliest convenience.  @edbratt and @m0mus are the assigned mentors from the Specification Committee to help guide you through this final process.  Feel free to reach out to any of us with questions.  Thanks!

**Comment by edbratt** [comment]
Any news to report regarding preparation of WebSocket materials for Jakarta EE ballot? From the Spec PR perspective, there are several items that need to be completed before we can begin the approval ballot for WebSocket. These should be itemized in the checklists associated with the Specification PR ([here](https://github.com/jakartaee/specifications/pull/234)).
A high-level summary is:
1. Complete the TCK
2. Complete the TCK result summary and publish it with your compatible implementation documents (Apache Tomcat 10*) -- this is referenced in the CCR
3. File the Compatibility Certification Request (CCR) issue (in websocket-api issue tracker) -- this example was from WebSocket 1.1: https://github.com/eclipse-ee4j/websocket-api/issues/308
4. Verify that the final version of the API JAR has been updated in the jakartaee-api project POM

Is there anything I can do, to help move this to ballot stage? Is there anything else blocking progress with this?

**Comment by markt-asf** [comment]
I am back after a few weeks away and am still working my way through the backlog of work that built up. I'm aiming to get to WebSocket this week.

**Comment by edbratt** [comment]
I just reviewed and fixed a small number of things in the TCK documentation (see [Jakarta EE TCK PR 492](https://github.com/eclipse-ee4j/jakartaee-tck/pull/492)). I believe the TCK docs are now sufficient for release. Please verify and approve. Once you are satisfied the TCK is running as expected and you have confirmed the zip file contents (look for a TCK built after Sep. 2, 2020), please add a comment to [this issue](https://github.com/eclipse-ee4j/jakartaee-tck/issues/395) so that the TCK will be promoted (and builds will stop).

**Comment by markt-asf** [comment]
@edbratt I've looked but I can't find a build dated later than Sept 2, 2020. The latest build I could find did not include the fixes you referenced in the previous comment.

**Comment by m0mus** [comment]
@markt-asf I confirm that there are no recent Websocket TCK builds. I asked @alwin-joseph to re-stage it https://github.com/eclipse-ee4j/jakartaee-tck/issues/395#issuecomment-691975129

**Comment by joakime** [comment]
Jakarta WebSocket 2.0.0 is still staged at https://jakarta.oss.sonatype.org/content/repositories/jakartawebsocket-1009/
Both the Server API jar and the Client API jar.
Been there since July 20th.
What's left?

**Comment by markt-asf** [comment]
I think it might need to be re-staged to pick up the JPMS module name changes,

**Comment by joakime** [comment]
Want me to  ...

1. drop the staged repo.
2. delete the `2.0.0-RELEASE` tag in git. - https://github.com/eclipse-ee4j/websocket-api/tree/2.0.0-RELEASE
3. merge `master` into the `2.0.0` branch to get the JPMS automatic module name changes - https://github.com/eclipse-ee4j/websocket-api/commit/a990b230d6f9e375855c9c121d89a4160a62a287
4. restage `2.0.0-RELEASE` from branch `2.0.0`? - https://github.com/eclipse-ee4j/websocket-api/tree/2.0.0

?

**Comment by joakime** [comment]
Perhaps even drop the `2.0.0` branch entirely and recreate it from `master` (as that branch contains now failed staged release commits and is sitting at 2.0.1-SNAPSHOT)?

**Comment by joakime** [comment]
Here's the list of differences between `master` and `2.0.0` branches - https://github.com/eclipse-ee4j/websocket-api/compare/master...2.0.0

**Comment by joakime** [comment]
@markt-asf opened PR #360 to reset the `2.0.0` branch to a state suitable for restage.  
If that gets accepted / merged, then steps 2 (remove bad tag) and 4 (restage) from above would still need to be done. (which I can do)

**Comment by markt-asf** [comment]
Personally, I'd drop the 2.0.0 branch entirely but I'll that choice up to you.

**Comment by joakime** [comment]
My tasks currently ...

- [ ] merge master into the `2.0.0` branch to get the JPMS automatic module name changes - a990b23
- [ ] Update `2.0.0` branch to be suitable for fresh release of version 2.0.0 - https://github.com/eclipse-ee4j/websocket-api/tree/2.0.0
- [ ] drop the staged repo.
- [ ] delete the `2.0.0-RELEASE` tag in git. - https://github.com/eclipse-ee4j/websocket-api/tree/2.0.0-RELEASE
- [ ] restage `2.0.0-RELEASE` from the updated branch `2.0.0` - https://github.com/eclipse-ee4j/websocket-api/tree/2.0.0

**Comment by joakime** [comment]
New staged `2.0.0` is available at the stage repository at https://jakarta.oss.sonatype.org/content/repositories/jakartawebsocket-1010/

Example: https://jakarta.oss.sonatype.org/content/repositories/jakartawebsocket-1010/jakarta/websocket/jakarta.websocket-client-api/2.0.0/

**Comment by joakime** [comment]
@markt-asf can I get a review of that staged websocket api?

**Comment by markt-asf** [comment]
LGTM.

**Comment by joakime** [comment]
I think this is done / completed.  right?

**Comment by markt-asf** [comment]
Closing as complete
